### ISSUE TITLE
Where is the environment.yml file?

### ISSUE THREAD

**Issue by whustone007** [JinyiW/GuidedDiffusionPur#1]
Hi!

When I want to run the command to install some necessary python packages by anaconda3 to run the code, I got an error that there is not a file "environment.yml". Can you help me?

**Comment by whustone007** [comment]
What's more, when I follow the instruction and run " python main.py --config configs/ImageNet_tpgd.yml", there is an error:

ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/slh/.conda/envs/diffusion/lib/python3.8/site-packages/pandas/_libs/window/aggregations.cpython-38-x86_64-linux-gnu.so)

Waiting for your help! Thanks.

**Comment by JinyiW** [comment]
Hi, thanks for your suggestion. We have uploaded the 'environment.yml' file. Hope it could help you. 
The error is not related with the environment. It is a GCC version problem. 
Best wishes!
